"""add rider location fields

Revision ID: 25bfbfae3e60
Revises: 72a7e6fb59e4
Create Date: 2026-05-07 07:35:03.143527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bfbfae3e60'
down_revision = '72a7e6fb59e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bodaboda_riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=False, server_default='true'))
        batch_op.add_column(sa.Column('current_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bodaboda_riders', schema=None) as batch_op:
        batch_op.drop_column('current_lng')
        batch_op.drop_column('current_lat')
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
